"""benchmarks/: every task fails on its fixture and passes once its solution overlay is applied.

Author: 최진호
Date:   2026-10-03

The shipped benchmark tasks are plain files, so they are checked without a model:
the verify command must fail on a fresh copy of the fixture (the agent is needed)
and succeed on the same copy with ``benchmarks/solutions/<id>/`` laid over it.
The long-horizon tasks in ``benchmarks/long/`` follow the same layout (``tasks/``, ``fixtures/``,
``solutions/`` below that directory), are generated by ``benchmarks/long/generate.py`` and get
extra structure checks.
"""

from __future__ import annotations

import importlib.util
import os
import shutil
import subprocess
import sys
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest
import yaml

ROOT       = Path(__file__).parents[2]
BENCH      = ROOT / "benchmarks"
LONG       = BENCH / "long"
TASKS_DIR  = BENCH / "tasks"
LONG_TASKS = LONG / "tasks"
TASK_FILES = sorted(TASKS_DIR.glob("*.yml")) + sorted(LONG_TASKS.glob("*.yml"))
LONG_FILES = sorted(LONG_TASKS.glob("*.yml"))
TIMEOUT    = 60
LONG_FIXTURE_LIMIT = 300 * 1024
LONG_FIXTURE_FLOOR = 100 * 1024

TOOL_FOR_TAG = {"node": "node", "c": "gcc"}


def _load(file: Path) -> dict[str, Any]:
    data = yaml.safe_load(file.read_text(encoding="utf-8"))
    assert isinstance(data, dict), f"{file.name}: a task file must hold a mapping"
    return data


def _solution_dir(file: Path, task: dict[str, Any]) -> Path:
    """The overlay of a task: ``solutions/<id>`` next to the ``tasks`` directory that holds the file."""
    return file.parent.parent / "solutions" / task["id"]


def _verify(command: str, workdir: Path) -> subprocess.CompletedProcess[str]:
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
    return subprocess.run(  # noqa: S602 - the command comes from the repository's own task file
        command, shell=True, cwd=workdir, capture_output=True, text=True, timeout=TIMEOUT, check=False, env=env,
    )


def _copy_fixture(task: dict[str, Any], file: Path, workdir: Path) -> None:
    fixture = (file.parent / task["path"]).resolve()
    shutil.copytree(fixture, workdir, ignore=shutil.ignore_patterns("__pycache__", ".git"))


def _require_tools(task: dict[str, Any]) -> None:
    for tag in task.get("tags", []):
        tool = TOOL_FOR_TAG.get(tag)
        if tool and shutil.which(tool) is None:
            pytest.skip(f"{tool} is not installed")


def test_there_are_tasks() -> None:
    assert len(TASK_FILES) >= 20


@pytest.mark.parametrize("file", TASK_FILES, ids=lambda f: f.stem)
def test_the_task_file_is_well_formed(file: Path) -> None:
    task = _load(file)
    assert task["id"] == file.stem
    assert task["path"] == f"../fixtures/{task['id']}"
    assert (file.parent / task["path"]).is_dir()
    tags = task.get("tags")
    assert isinstance(tags, list) and tags and all(isinstance(t, str) and t for t in tags)
    for key in ("prompt", "verify"):
        assert isinstance(task[key], str) and task[key].strip()
    for key in ("max_turns", "max_cost_usd", "timeout"):
        assert task[key] > 0


@pytest.mark.parametrize("file", TASK_FILES, ids=lambda f: f.stem)
def test_verify_fails_on_the_untouched_fixture(file: Path, tmp_path: Path) -> None:
    task    = _load(file)
    _require_tools(task)
    workdir = tmp_path / "work"
    _copy_fixture(task, file, workdir)
    result = _verify(task["verify"], workdir)
    assert result.returncode != 0, "verify already passes: the task needs no work"


@pytest.mark.parametrize("file", TASK_FILES, ids=lambda f: f.stem)
def test_verify_passes_with_the_solution_overlay(file: Path, tmp_path: Path) -> None:
    task     = _load(file)
    _require_tools(task)
    solution = _solution_dir(file, task)
    assert solution.is_dir(), f"no solution overlay for {task['id']}"
    workdir  = tmp_path / "work"
    _copy_fixture(task, file, workdir)
    shutil.copytree(solution, workdir, dirs_exist_ok=True, ignore=shutil.ignore_patterns("__pycache__"))
    result = _verify(task["verify"], workdir)
    assert result.returncode == 0, f"stdout:\n{result.stdout[-1500:]}\nstderr:\n{result.stderr[-1500:]}"


# ---------------------------------------------------------------------------
# Long-horizon tasks (benchmarks/long)
# ---------------------------------------------------------------------------


def _fixture_bytes(file: Path) -> int:
    fixture = file.parent.parent / "fixtures" / file.stem
    return sum(p.stat().st_size for p in fixture.rglob("*") if p.is_file())


def _load_bench_agent() -> ModuleType:
    spec   = importlib.util.spec_from_file_location("bench_agent_long", ROOT / "scripts" / "bench_agent.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["bench_agent_long"] = module
    spec.loader.exec_module(module)
    return module


def test_there_are_eight_long_tasks() -> None:
    assert len(LONG_FILES) == 8


@pytest.mark.parametrize("file", LONG_FILES, ids=lambda f: f.stem)
def test_a_long_task_carries_the_long_contract(file: Path) -> None:
    task = _load(file)
    assert "long" in task["tags"]
    assert task["max_turns"] == 80
    assert task["max_cost_usd"] == 1.0


@pytest.mark.parametrize("file", LONG_FILES, ids=lambda f: f.stem)
def test_a_long_fixture_is_large_enough_to_grow_the_history_and_small_enough_to_commit(file: Path) -> None:
    size = _fixture_bytes(file)
    assert LONG_FIXTURE_FLOOR <= size < LONG_FIXTURE_LIMIT, f"{file.stem}: {size} bytes"


def test_the_short_tasks_do_not_carry_the_long_tag() -> None:
    for file in TASK_FILES:
        if file not in LONG_FILES:
            assert "long" not in _load(file)["tags"], file.name


def test_the_generated_files_equal_a_fresh_generation() -> None:
    env    = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
    result = subprocess.run(  # noqa: S603 - runs the repository's own generator
        [sys.executable, str(LONG / "generate.py"), "--check"], capture_output=True, text=True, timeout=120, check=False, env=env,
    )
    assert result.returncode == 0, result.stdout[-1500:] + result.stderr[-500:]


def test_bench_agent_loads_the_long_tasks_and_selects_them_by_tag(capsys: pytest.CaptureFixture[str]) -> None:
    bench = _load_bench_agent()
    tasks = bench.load_tasks(LONG_TASKS)
    assert len(tasks) == len(LONG_FILES)
    assert all("long" in t.tags and t.max_turns == 80 and t.max_cost_usd == 1.0 for t in tasks)
    assert bench.main([str(LONG_TASKS), "--tag", "long"]) == 0
    assert f"{len(LONG_FILES)} task(s)" in capsys.readouterr().out
    assert bench.main([str(TASKS_DIR), "--tag", "long"]) == 2
